export const MessageConstants = {
    USER_NOT_FOUND : "user not found",
    INTERNAL_SERVER_ERROR : "Internal server error ocured please try again later",
    INVALID_PASSWORD : "Invalid password",
    REQUIRED_FIELDS_MISSING : "Required fields are missing",
    LOGIN_SUCCESS : "Login successful",
    REGISTER_SUCCESFUL : "Successfully registered",
    EMAIL_REQUIRED : "Email is Required",
    OTP_SEND  : "Otp Send successfully",
    EMAIL_AND_REQUIRED : "Email and Otp are required",
    INVALID_OTP : "Invalid OTP",
    OTP_VERIFIED : "Otp verified and user registerd successfully",
    OTP_RESEND :"Otp resend Successfully",
    SIGNOUT_SUCCESFUL : "Logout Successfully",
    ID_TOKEN_REQUIRED : "Id token required",
    GOOGLE_SIGNIN_SUCCESS : "Google SignIn success",
    GOOGLE_SIGNIN_FAILED : "Google SignIn Failed",
    LOGIN_FAILED : "Login Failed",
    LOGOUT_SUCCESS :"Logout successfull",
    ALL_USERS_RETRIEVED : "All users retrieved",
    USER_ID_REQUIRED : "User Id is required",
    USER_BLOCKED : "User is Blocked",
    USER_UNBLOCKED : "User is Unblocked"
}
